name: crow_dev
channels:
  - conda-forge
dependencies:
  - black
  - clmm
  - hypothesis
  - isort
  - numcosmo >= 0.21.1
  - numpy >= 2.0
  - pip >= 20.1
  - pyccl >= 2.8.0
  - pytest
  - pytest-cov
  - python >= 3.11
  - python-build
  - scipy >= 1.12
